echo "-----------------------------------------"
echo "FIO Utilities"
echo ""
echo "/usr/bin/fio-attach"
echo "  Exports an ioMemory device as a block device."
echo "/usr/bin/fio-beacon"
echo "  Enables or disables a beacon at the specified device node."
echo "/usr/bin/fio-bugreport"
echo "  Generates a bugreport which you can send to no one."
echo "/usr/bin/fio-detach"
echo "  Unexports a fusionio device as a block device."
echo "/usr/bin/fio-format"
echo "  Performs a low-level format of the device."
echo "/usr/bin/fio-get-erase-count"
echo "  Gets erase count statistics."
echo "/usr/bin/fio-iodrive.sh"
echo "  Displays serial information for the device."
echo "/usr/bin/fio-pci-check"
echo "  Checks for errors on the PCI bus tree."
echo "/usr/bin/fio-proctl"
echo "  Displays some device info of some kind."
echo "/usr/bin/fio-read-lebmap"
echo "  Dumps the current LEB map for an ioDrive and writes the map to standard output."
echo "/usr/bin/fio-sanitize"
echo "  Deprecated version of fio-sure-erase."
echo "/usr/bin/fio-status"
echo "  Prints out various statistics and data related to all ioMemory devices discovered in the system."
echo "/usr/bin/fio-sure-erase"
echo "  Securely erase data from the ioMemory device."
echo "/usr/bin/fio-update-iodrive"
echo "  Updates the ioMemory device's firmware."
echo "-----------------------------------------"
